apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jmrrvp5mk-go 
  janus-idp.io/tekton: jmrrvp5mk-go
  backstage.io/kubernetes-id: jmrrvp5mk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jmrrvp5mk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml