apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jmrrvp5mk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jmrrvp5mk-go 
  name: jmrrvp5mk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jmrrvp5mk-go 
